name: Release Docker Image
on:
  push:
    branch:
      - testing

jobs:

  release:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
      - name: Get version without v character
        id: version
        run: |
          VERSION=4.0.1
          VERSION_WITHOUT_V=4.0.1
          echo "value=${VERSION_WITHOUT_V}" >> $GITHUB_OUTPUT

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ayush706020
          password: dockerayushnau

      # This workflow triggers on GitHub Release, but it may start before the npm package is published.
      - name: Sleep for 1s seconds
        run: sleep 1s

      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:apps/generator"
          push: true
          load: false
          build-args: |
            ASYNCAPI_GENERATOR_VERSION=4.0.1
          tags: |
            ayush706020/generator:4.0.1
            ayush706020/generator:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha
      - name: Run pwd
        run: |
          pwd
          ls -lh
          cd ../
          ls -lh
          pwd
          ls -lh
          cd ../
          ls -lh
          pwd
      - name: Update Docker Hub Readme
        uses: meeDamian/sync-readme@v1.0.6
        with:
           user: ayush706020
           pass: dockerayushnau
           slug: asyncapi/generator
           readme: ../README.md
           description: Use your AsyncAPI definition to generate literally anything. Markdown documentation, Node.js code, HTML documentation, anything!
